### ISSUE TITLE
Unable to list Taiga projects or convert over SSL

### ISSUE THREAD

**Issue by pdeffendol** [taigaio/redmine-migrator#4]
I have Taiga 1.9.0 successfully installed and running with Apache 2.4 as a proxy to the back and front ends and SSL-enabled.  I am trying to run the Redmine converter and cannot get it to work unless I disable SSL on the Taiga side.  

The converter console shows an error message but it's not helpful:

```
Mon Nov 02 13:36:17 MST 2015    ERROR   gui.controller.MigrationProgressAwareController Exception while migrating: Cannot get property 'contentAsString' on null object
```

**Comment by mariogarcia** [comment]
Probably is because you need to install your Taiga certificate using `keytool`
- Download your Taiga certificate from the browser
- Install it using the following command:
  
  ```
  keytool -importcert -alias taiga -file /path/to/certificate.crt -noprompt -storepass changeit -trustcacerts -keystore $JAVA_HOME/jre/lib/security/cacerts
  ```

This command installs your `certificate.crt` file (change the path and the name to the one you downloaded before) into the `cacerts` keystore using the default password `changeit`. The `$JAVA_HOME` variable is often present, if not it should point at your Java installation root folder. BTW `changeit` is the default password so don't change it if you don't want to.

Many Java programs use the default JVM keystore when trying to do a SSL connection.

**Comment by pdeffendol** [comment]
Thanks, that did it.  Note to future readers, I'm on Mac OS X (El Cap) which at first only had the default JRE that does not include `keytool`.  I had to download and install a full JDK first.

In addition, it seems that the Mac OS "Jar Launcher" that runs when you double-click a .jar file will use the system Java.  Run the converter from the command line with `java -jar [filename].jar` instead.
